### ISSUE TITLE
Running Automated Tasks with a CronJob

### ISSUE THREAD

**Issue by diguage** [diguage/kubernetes-notes#90]
[Running Automated Tasks with a CronJob](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/)

## Abstract

You can use CronJobs to run jobs on a time-based schedule. 

1. create a CronJob by YAML:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
2. create a CronJob by command:
```bash
kubectl run hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"
```
3. Get CronJon
```bash
kubectl get cronjob hello
kubectl delete cronjob hello
```
